### ISSUE TITLE
Suggestions for 1 Key Character Cycle

### ISSUE THREAD

**Issue by Saellys** [Clam-/TraditionalT9#12]
It's quite convenient that most of the text symbols you can type are able to be cycled through on the 1 key, however I personally find that the lack of the Apostrophe ( ' ) in the cycle is bothersome. It was suggested to me by Clam- to start this thread to suggest a new cycle of symbol characters for the 1 key.
This way, other users of the T9 IME can pitch in as well.

**Comment by Saellys** [comment]
My assertion is that the Underscore ( _ ) is used quite infrequently in text messaging, and could be replaced with the Apostrophe ( ' ) as a more useful character to access quickly. Thus the cycle would look more like this in my proposition:
. , ? ! ' " / - @ $ % & * ( ) 1
Where the Apostrophe ( ' ) is added in right before the Quotation Mark ( " ) and the Underscore ( _ ) is removed from the listing.

However, I've also found it a bit of a pain to access the 1 character like this after having to cycle through all the others, and suggest that it be placed 6 characters away from the start of the cycle to match most of the other keys:
. , ? ! ' " 1 / - @ $ % & * ( )

This way you can access the actual numerical symbol using the same number of key presses typically required for the other keys, but the rest of the common symbols are still accessible.
That's about all I have for suggestions on the order of the 1 key's cycle. I can't at the moment think if any of the other symbols should be reordered as I haven't been texting long.

**Comment by Clam-** [comment]
Sorry for the delay on getting to this and thank you for your time and effort for reporting this in detail.
Unfortunately I haven't got around to addressing this yet, but it's something I will be reviewing and modifying. 
I was going to dig up one of my old Sony Ericssons to see what the cycle looked like on that but I can't seem to find any.
By the way, there's no fixed limit to how many characters can appear on the cycle (other than practicality).

For the Colon and Semicolon, I've learned the key combination for the "Insert Symbol" route of entering symbols, but perhaps we can at least add Colon to the cycle?
I like your orderings and I will most likely use the latter of your suggestions when I revisit this.

Thanks again.

**Comment by Saellys** [comment]
Cool, glad to help! As I discussed over on XDADevelopers my biggest issue with accessing symbols is that using the Insert Symbol on the touchscreen causes the caps to break. 
I personally believe 0 can be used similar to 1 with plenty of auxiliary symbols, any on 1 that you'll be replacing and even some more that weren't discussed already (While putting "0" six symbols in like on 1). Maybe a single symbol could get added to the end of each normal numerical key's cycle as well, but that may get somewhat confusing...

**Comment by iaros** [comment]
Also need to unify those symbols on 1, 0 and # across different layouts.
And maybe give options in the menu, i.e. Sony-Ericsson style, Nokia style, Siemens style, Samsung style or just force something uniform.

**Comment by Clam-** [comment]
Options for the styles might work, because they only modify the way 0 and # handles, don't they? If someone can find or make a write up of what is exactly mapped to what for the different styles, it'll make it easier to implement/plan.

Also sorry for the lack of activity.

**Comment by iaros** [comment]
In Qualcomm featurephones in Verizon:
1 - .@?!-,&:'/1
# - space
0 - 0

**Comment by iaros** [comment]
Old Siemens x55 series:
```
1 - <space><return>1
# - switch case
0 - .,?!'"0-()@/:_+~&
* - list of symbols to choose from
```

**Comment by Kallemies** [comment]
Could it be possible to make it so that you can navigate through the symbols with using the navigation key  instead of pressing the number 1 multiple times?

**Comment by Clam-** [comment]
Depending on what mode you are in you can use Up and Down to navigate through the "suggestions". However in Text Mode it will commit the selected character after a very brief time. I should reset the timer when using up and down keys.
If that is not what you meant please elaborate.
Again, sorry iaros for the lack of development.

**Comment by Kallemies** [comment]
Hi, this is what I mean by choosing the symbols with the navigation key.
I basically would like to see the symbols selection to be done like in my other phone, Uniwa N2.
In the Uniwa N2, you press once the key * and you get a horisontal list of all the symbols.
You can select the symbols by highlighting them with the navigation key and then pressing confirm.
Picture is from Uniwa N2.

![bb17ec6f-b7e9-47af-9508-54198a8c899d](https://user-images.githubusercontent.com/42135570/43728169-e7bd570a-99ac-11e8-9f11-2c77f4ce9149.jpg)
