### ISSUE TITLE
How to type a blank space?

### ISSUE THREAD

**Issue by alfonsodm** [Clam-/TraditionalT9#13]
None of the keyboard numbers types a blank space. Usually, 0 key writes a space, like traditional Nokia T9.

**Comment by Clam-** [comment]
There is an option "Space on 0 key" for people that are more familiar with Nokia layout. You can access the "Traditional T9 Settings" in the "Language and Keyboard" setting, or by long pressing Softkey Right while the IME is active.

This is in the very latest version that for some reason I haven't put on the Google Play Store yet.
http://nyanya.org/android/TraditionalT9-git-e08c4a4.apk

I'll put it on the Play Store tomorrow.

**Comment by Clam-** [comment]
I've now pushed that build to the Play Store. It should probably also be noted that by default space is on the # (pound) key, since I was more familiar with the SE layout than the Nokia layout. 
Now you can choose to have it on the 0 key.

**Comment by alfonsodm** [comment]
Thank you so much por the new apk, since I can`t install it from google play as it says it's not compatible with my device. FYI it's an android TV box with no physical keyboard but with a remote control with Nokia style numeric keypad. I think your app is very useful for this use, when you don`t need a full keyboard and mouse to use it as a media center but sometimes you need to type something.
