### ISSUE TITLE
Key Remapping?

### ISSUE THREAD

**Issue by surya27895** [Clam-/TraditionalT9#15]
how to remapping : 
" * " key to insert  " * " character
" * " key long press to insert symbol
"#" key to change case
"#" key long press to number case
and
triple press 0 key to new line ?

i want bring back that function like old nokia phones
thxs

**Comment by Clam-** [comment]
Remapping doesn't quite change the functionality of the button with new functionality, it simply "swaps" keys.

The current key settings are:
Soft Left: Insert Symbol (or Add Word depending on context)
*: Change case (Long press, change language or insert Smiley if single language)
#: space/newline (long press new line always)

So if you wanted to get as close to "Nokia layout" as possible with remapping, you could attempt to remap * and #, but that would only partially get you where you want to be.

triple press 0 in alphabet mode should give you new line if you have "Space on 0 key" enabled. This is a bug and something I'll address.

Making the traditional Nokia layout true to form (while also keeping the option for the current Sony Ericsson layout) is much more complicated with the IME in it's current state and most likely something I'll not be able to address in the short term. 
It would be possible for someone to take the current code and change it to work like Nokia layout ignoring the current layout.
