### ISSUE TITLE
vkworld t2 compatibility

### ISSUE THREAD

**Issue by Corerox** [Clam-/TraditionalT9#20]
Hi,
Is there a way to make this app compatible with the vkworld t2 ?
He come with a built in t9 physical keyboard, but no good app to use it...
This app seem to do the trick, please make it usable ;)

Thanks in advance !

**Comment by Clam-** [comment]
I can not find any mention of "vkworld" in the Play Store model database. It may have a different model name or code name that I don't know about.
Regardless, please check the response here:
#14 
It seems these manufacturers aren't giving Google correct information about their hardware.

My App specifically targets keypad hardware, and will not allow installation on devices that don't report having keypads.

Sorry for the inconvenience. You can always sideload the APK directly.

**Comment by Corerox** [comment]
Thanks for this fast answer, did as you said and download the apk directly, and it work just fine on the phone :)
Thanks a lot
