### ISSUE TITLE
Update to Latest

### ISSUE THREAD

**Issue by harimaruthachalam** [Clam-/TraditionalT9#21]
The project is not compatible with Android Studio 3.0. Is there any plan to update the project?

**Comment by Clam-** [comment]
Yes, I was working on updating the Gradle scripts but I don't have a lot of time to work on the project so updates are slow. Sorry for the inconvenience.

**Comment by harimaruthachalam** [comment]
Thanks for the response. Hope you will update the Gradle soon.
