### ISSUE TITLE
Feature request: Lithuanian language

### ISSUE THREAD

**Issue by ghost** [Clam-/TraditionalT9#23]
Hi there,
Just tried (after long hours of searching) Traditional T9 keyboard on a Japanese android flip phone made by just5 and it's awesome. It would be great if it would have more input languages tough. Not having much programming skills my self, I am wondering, would it be hard to add Lithuanian to the list of input languages?

**Comment by Clam-** [comment]
Hi,
Thanks for the input. Input languages are not a trivial thing since they require a fair bit of work and knowledge about the language itself.
Here's a page with a description of the tasks involved. If you can't do any of the code modifying parts that's fine, I can do those so long as there's instruction on what needs to be done.

I have very little personal time though and it's likely that any work you do won't be able to be acted on for at least a few weeks.

**Comment by iketanijus** [comment]
Thank you very much for response! 
As much as it would be great to have this support fast, I do appreciate that writing language support for some foreign language would most likely be tedious process to some degree. But I'm really happy to hear that you would be willing to for see this request at your discretion! 

That said, I've read the wiki page on adding input languages and have in fact attempted to do it, but with my programming skills it would take ages to compile into a working apk :) Anyhow, Lithuanian language uses the same alphabet as English does (at least in computer input cases), but we have a few additional letters: ą, č, ę, ė, į, š, ų, ū and ž. Plus quotation marks are a little bit different („qote“ insted of English "qote").

Here is what I have attempted to do: 

CharMap.java:
https://pastebin.com/X7Q41yya

LangHelper.java:
https://pastebin.com/vFSi4E8i

const.xml
https://pastebin.com/SA7D1qrj

arrays.xml:
https://pastebin.com/xAdBkdnW

I have also attempted to setup android-studio and tried to compile the code. Here things start to go high wire. Sometimes code builds by running make. But once I try to build apk, it complains either about not finding some path. Nor finding java compiler (but I do have latest JDK) or sometimes it does complain about not finding some stuff regarding my newly added language. 

So it would be much appreciated if you could make any sense of this.

**Comment by iaros** [comment]
Hello, I added once Ukrainian language. I can a take a look into your issue.
