### ISSUE TITLE
App doesn't allow it to be opened after install (Samsung Galaxy Folder SM-G150)

### ISSUE THREAD

**Issue by iop223** [Clam-/TraditionalT9#25]
When installing from the playstore or directly from the APK, there is no option to open the app and the shortcut isnt being created. Is there a compatibility issue with the Samsung Galaxy Folder? It doesn't show up in installed keyboards either.

**Comment by Clam-** [comment]
Hi,

The app doesn't actually have a launcher, or a shortcut. It's activated entirely within the languages/keyboards UI options.
I'm not sure how the Samsung OS handles keyboards and I don't have a device to test that sorry.

**Comment by iop223** [comment]
Hi, thanks for the quick reply. I've managed to get it working somehow as
it is showing up in the installed keyboards now.

**Comment by friapro** [comment]
Do you know what you did to get it working, @iop223? I have the same phone, and the same problem as you evidently had. Which version of the app are you using?
