### ISSUE TITLE
Interference with Touch Cruiser on SH-01J

### ISSUE THREAD

**Issue by vladkorotnev** [Clam-/TraditionalT9#29]
Hello,

First of all, thanks for the awesome IME. I'm using it on my Docomo SH-01J for Russian text and I've noticed that whenever TraditionalT9 is enabled, I cannot use Touch Cruiser function by holding down the Answer key. When Docomo input is active, it works fine, but with TraditionalT9 it's intermittent (sometimes works, sometimes doesn't).

Does TT9 intercept some input systemwide that may cause such problem?

**Comment by Clam-** [comment]
Hi,

Yes by nature of what the IME does it intercepts input systemwide.
In most cases, unless those button presses are supposed to do something IME-wise, it's usually passed through/not handled and should function normally (however some devices do some weird low level things on their own, too).
I did have a SHF31 which had the "Touch Cruiser" functionality, however I lent it away and no longer have access to it so I'm unsure if I'll be able to test/fix anything specific to that functionality.

If you can provide some additional information, it might help in identifying if the issue can be resolved easily or not:
* Are you using the Key Remap functionality?
* Does holding answer key not enter touch cruiser mode if the IME UI is displayed? (The gray UI element that shows at the bottom of the screen). That UI element can usually be toggled by pressing Centre Dpad when in an input field.
* Are there particular UI elements that when active cause the long press answer key to not enter Touch Cruiser mode? For example, if scrolling in a webview it always works, or if when in an active input field it never works, or works when in a number field, etc.)
* Is there a particular app where it always or never works?
* Any other conditional that you may be able to identify

**Comment by vladkorotnev** [comment]
Thanks for the quick response.

> Are you using the Key Remap functionality?

No, I'm only using the standard input functionality. Changing Input/Dictionary modes doesn't help with the touch cruiser problem.
 
> Does holding answer key not enter touch cruiser mode if the IME UI is displayed? (The gray UI element that shows at the bottom of the screen). That UI element can usually be toggled by pressing Centre Dpad when in an input field.

No, it never enters touch mode as long as TT9 is set as the active IME in settings. It won't activate automatically when opening apps e.g. Browser either.

> Are there particular UI elements that when active cause the long press answer key to not enter Touch Cruiser mode? For example, if scrolling in a webview it always works, or if when in an active input field it never works, or works when in a number field, etc.)

As mentioned above, it doesn't relate to whether TT9 is *active*, but whether it's *enabled* at all it seems. I'm using Nova Launcher if that may cause any issue, however even at the Nova screen I'm unable to enter the touch cruiser mode as long as TT9 is enabled.

Additionally I noticed, in the gray bar the software keys never work as well. So I can't change the input mode within TT9 other than by going to TT9 Settings and changing between Dictionary/Direct from there.

**Comment by Clam-** [comment]
Hmm, I may be a little confused. When you say "intermittent (sometimes works, sometimes doesn't)" under what conditions does it work?

After testing on a few different phones, not all follow the same key scheme. You may want to use a key event viewer app to know what your softkeys are.
On the 007SH they were correctly mapped, but on my current phone, softkey left is actually something like pageup or something strange.
Once you know what the top left key is for example, you can use the remapping feature to hopefully let you control the UI with the softkeys (there's a wiki page explaining more).

**Comment by vladkorotnev** [comment]
I was too fast to say it's intermittent, because now it's 100% reproducible :/

Set "chosen keyboard" in settings to TT9 → cruiser doesn't work at all
Set "chosen keyboard" to docomo input → cruiser works

It's as if docomo input is constantly monitoring the keyboard and starting cruiser on it's own, rather than passing the event down to some other daemon.

I'm not very familiar with Android's input model, are IMEs constantly active and not just when a text field is active?

**Comment by Clam-** [comment]
In a sense IMEs are constantly active, although the IME gets a signal everytime the "current context" changes, so it can choose not to do anything or it can display a UI widget on specific contexts, etc.
You can think of the IME as literally a virtual keyboard... and that's what later versions of Android call it in the settings "virtual keyboard". Yes the Virtual Keyboard can also handle the literal hardware keys.

It's possible that the Sharp IME specifically makes a certain Intent which turns on the cruiser, or it's possible that the cruiser is part of the Sharp IME itself. Speaking of the latter, I never really thought about it before but I suppose there's no reason why I couldn't implement something like "mouse keys" internally, assuming android has some kind of accessibility api for manipulating a virtual mouse.

If it's the former, and you are able to know the Intent calling parameters, there's no reason why one wouldn't be able to call it directly. If it's the latter, then it would be impossible unless it was a module thing that was able to be called externally.

As I said I don't have a Touch Cruiser device anymore so I'm unable to investigate the specifics of how the Touch Cruiser is activated so I would need information from yourself or others on the specifics of it.

I suppose there's still some unanswered questions which may shed some more light on the situation:
* Did it ever work with TT9? Are you absolutely certain?
* Does it work with other IMEs? (you'll likely need to test with minimal IMEs like the AOSP default core IME, as other fancy IMEs like swipe keyboards and such may totally ignore all hardware keys entirely)

**Comment by vladkorotnev** [comment]
Sadly no, I'm not certain it worked with TT9, maybe it was a brain fart after all, since now I jump back and forth between IMEs all the time. 

Just tested and the result is:

* TT9 + Nova launcher: no cruiser
* TT9 + docomo launcher: no cruiser
* docomo input + Nova launcher: cruiser works in launcher and apps
* AOSP input + Nova launcher: cruiser works in launcher and apps 

Is there some way I could attach a debugger to an IME, or logcat something more helpful? I'm not very experienced with Android development but I could probably get Android Studio and try to acquire more info.

**Comment by vladkorotnev** [comment]
Maybe this might be of some clue:

```
D/NotificationService(  824): key: 0|android|0|InputManager|1000
D/NotificationService(  824): key[0]: 0
D/NotificationService(  824): key[1]: android
D/NotificationService(  824): key[2]: 0
D/NotificationService(  824): key[3]: InputManager
D/NotificationService(  824): key[4]: 1000
V/BgRingerService(  824): bgRingerStartEx call pkg:android id:0
V/BgRingerService(  824):  UserHandle:UserHandle{0}
D/BgRingerService(  824): ringTimeSetting() streamType = 5, category = 5
D/NotificationService(  824): key: 0|android|0|InputManager|1000
D/NotificationService(  824): key[0]: 0
D/NotificationService(  824): key[1]: android
D/NotificationService(  824): key[2]: 0
D/NotificationService(  824): key[3]: InputManager
D/NotificationService(  824): key[4]: 1000
D/NotificationService(  824): changeNotificationListCount count=6 mNotificationListCount=6
D/NotificationData( 2424): key: 0|android|0|InputManager|1000
D/NotificationData( 2424): key[0]: 0
D/NotificationData( 2424): key[1]: android
D/NotificationData( 2424): key[2]: 0
D/NotificationData( 2424): key[3]: InputManager
D/NotificationData( 2424): key[4]: 1000
D/StatusBar( 2424): key: 0|android|0|InputManager|1000
D/StatusBar( 2424): key[0]: 0
D/StatusBar( 2424): key[1]: android
D/StatusBar( 2424): key[2]: 0
D/StatusBar( 2424): key[3]: InputManager
D/StatusBar( 2424): key[4]: 1000
D/NotificationData( 2424): key: 0|android|0|InputManager|1000
D/NotificationData( 2424): key[0]: 0
D/NotificationData( 2424): key[1]: android
D/NotificationData( 2424): key[2]: 0
D/NotificationData( 2424): key[3]: InputManager
D/NotificationData( 2424): key[4]: 1000
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
E/ExpandableNotificationRow( 2424): setExpansionDisabled return
```

I get those logs (always the same) whenever I enable/disable cruiser with the docomo IME, but not when I hold down the cruiser button with TT9.

Is there some utility to view what is posting the notification and what are the contents so then I could reproduce it inside TT9?

**Comment by Clam-** [comment]
Those log entries unfortunately are not helpful. It seems to be just related to the actual notification that comes up with you enable cruiser.
If AOSP keyboard makes this work then it should work with TT9. It's possible that the long press isn't being sent to the OS correctly.

I will have a little poke around but I do not have time to do any significant investigation/big changes unfortunately.

**Comment by vladkorotnev** [comment]
Ah indeed, I was confused thinking it means Notification as in Inter-Process Notification, not as User Notification :-)
I'll get android studio later today and try messing around in the debugger, thanks for your help anyway

**Comment by Clam-** [comment]
I've had to do quite a few hacky things to handle weird android edge cases, so I may be consuming more input than needed in onKeyDown and onKeyUp for example: https://github.com/Clam-/TraditionalT9/blob/master/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L619
When that method returns true, the input is consumed and not sent to the application to handle.
You may want to play around with seeing what events fall through to returning true and such. Be wary through that if the key is handled inside the IME and also returns false, then you may get double input.

**Comment by vladkorotnev** [comment]
Yes, I have traced the method you linked to and indeed it goes down the route of sendKeyEvent → return true. That is, when at launcher screen, thus no input field is active. Probably that might be the cause, I'll try later this evening.

Now I've got more ideas to implement, I'll also try having a go at importing pre-heated dictionaries (not wordlists, but wordlists+frequencies, as the default one seems to type nonsense when freshly installed).

And maybe if I can reverse the cruiser hardware, then also do a thing for "commit current letter on finger lifted from keypad" in direct mode — that would make things fast enough to make dictionary mode fairly irrelevant :-)

**Comment by Clam-** [comment]
If you notice:
https://github.com/Clam-/TraditionalT9/blob/6e9cc238e7b35eaadadadb2a62a74a3de268a536/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L606
https://github.com/Clam-/TraditionalT9/blob/6e9cc238e7b35eaadadadb2a62a74a3de268a536/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L516

If in non-edit mode that should return false anyway, launcher should have something like inputtype 0 or such:
https://github.com/Clam-/TraditionalT9/blob/6e9cc238e7b35eaadadadb2a62a74a3de268a536/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L254

I suspect there may be a bug when using key remap mode:
https://github.com/Clam-/TraditionalT9/blob/6e9cc238e7b35eaadadadb2a62a74a3de268a536/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L607
That should probably be !keyRemap, maybe. But if you aren't using keyremap key should always equal null anyway.

The "backup dictionary" and "restore dictionary" features include frequency.
If you wanted to import a dictionary+frequency the easiest way would be to take a backup, look at the txt that is saved and then convert your dict+freq data in to the txt structure that TT9 expects for restoring (I believe it's just space separated [word, freq, lang])
https://github.com/Clam-/TraditionalT9/blob/6e9cc238e7b35eaadadadb2a62a74a3de268a536/src/org/nyanya/android/traditionalt9/TraditionalT9Settings.java#L587

**Comment by vladkorotnev** [comment]
Yes, the top functions you linked, I think, go to `return super` and then, it seems, `super` returns `false` that causes the sendKeyEvent route to happen. (I'm not 100% sure so I'll check that again later)

For the import, I plan to use the data from Luminoso Insight https://github.com/LuminosoInsight/wordfreq/tree/master/wordfreq/data

It's in msgpack format, which is more reliable than CSV/TSV/SSV, but also organized differently, in any case, it won't be too hard to implement. Adding some way of easily adding a new word and assigning it the frequency of (max frequency per same pattern + 1) so it appears on the top unless used just once — will be a more difficult task, especially UX-wise (wish I still had some of my old Nokia phones to remember how they did that).

**Comment by vladkorotnev** [comment]
Yes, that was it, the keyRemap check. And keyRemap key is not null, it's same as input. I've corrected the offending check, please see #30 .

**Comment by Clam-** [comment]
Nice. Tomorrow I'll go about doing another build (hopefully if my build environ still works) and push it to the googly store.

**Comment by vladkorotnev** [comment]
You might wanna wait a bit for my fork to be relatively complete as I'm fixing the layout on SH-01J being garbled, as well as soft-keys.

Already found a bug where a dictionary backup with multiple languages will end with an error.

**Comment by vladkorotnev** [comment]
Pushed the fork, hope it's good enough! Thanks for the awesome project.
