### ISSUE TITLE
Auto pop-up

### ISSUE THREAD

**Issue by beSpit** [Clam-/TraditionalT9#35]
On the Messaging app of most Android devices, when opening a conversation thread, the keyboard won't pop-up until one will tap the text box.

This is caused by adding `android:windowSoftInputMode=stateHidden` to the Messaging app.

However, when using a hardware keyboard (with the Traditional T9 app), it would be quite convenient if the interface handler always becomes active - regardless of what the Messaging app (etc) manifest says.

I have seen many keyboard apps which are meant to communicate with the hardware keyboard which do so (eg. Kika, in one of their versions). 

Would you know how I can achieve this? 
What code am I supposed to add to the TraditionalT9.java, to tell him to ALWAYS bring up the full interface handler?

Many thanks!

**Comment by Clam-** [comment]
Yes, I have noticed that on some applications, too. Usually I press DPAD_CENTER to toggle the input UI in these cases.
If you want to investigate yourself, for a particular application this would be the function to look at:
https://github.com/Clam-/TraditionalT9/blob/master/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L249
If the application defines it's textbox as a weird input box, it may be getting caught by this check:
https://github.com/Clam-/TraditionalT9/blob/master/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L254

You may want to also look at this method:
https://github.com/Clam-/TraditionalT9/blob/a352deca43c9b81152ddae7d2a551bc1be10b563/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L115

You may want to play with uncommenting this section:
https://github.com/Clam-/TraditionalT9/blob/a352deca43c9b81152ddae7d2a551bc1be10b563/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L123

I don't remember the conclusions I came to when playing with that particular functionality, sorry. The Android ecosystem varied greatly on how it behaved in various circumstances on different versions of Android.

Good luck.

**Comment by Clam-** [comment]
Sorry I forgot to add, the DPAD_CENTER code for toggling the UI may also be of assistance:
https://github.com/Clam-/TraditionalT9/blob/a352deca43c9b81152ddae7d2a551bc1be10b563/src/org/nyanya/android/traditionalt9/TraditionalT9.java#L927

You may simply want to add a "showwindow" call in the inputstart function.
