### ISSUE TITLE
Support Cat S22 Flip

### ISSUE THREAD

**Issue by thw26** [Clam-/TraditionalT9#43]
I've recently purchased a CAT S22 Flip. It comes by default with a modified version of the Kika keyboard app and it's "T9" functionality is not T9 (use # key to change input mode, select key, press center select to choose key). The phone would be greatly benefited by having access to this app!

When I got to the Google Playstore, the app shows as being unavailable for the CAT S22 Flip. The device runs Android 11 Go by default. It's keys are a little different from a standard phone from decades ago. You can see the keyboard here:

https://www.t-mobile.com/content/dam/tfb/assets/foreground/device/TFB-CATOfferS22-Full-CatS22-desktop.jpg

It has a volume rocker on the right, a special key on the left, then the phone's keypad has three sections:

- The standard Android buttons:
  - Android Back, Android Home, Android Menu
- A section for calls
  - An activate speaker key on top of a call button that either answers a call or opens the phone app
  - Next to it are the standard four arrow keys with center select
  - Next to this is a "Clear" button that functions as backspace on top of an end call button.
- Beneath this is the standard 10 digits, star, and pound keys.

What else might you need from me in order to make your software compatible with this device?

**Comment by Clam-** [comment]
Sorry, I don't really have the time and drive to work on this project any longer. The only requirement I specify in the Play Store manifest is the device must have a physical keyboard/keypad. Clearly a lot of phone manufacturers are not setting their phone manifest specification correctly :(

You can get around this by sideloading the app by downloading the APK from an APK mirroring website. If I was smarter I would have put released APKs on the releases section of the GitHub, sorry for my incompetence.

The Input method should work on that key layout, probably. I think I've seen people mentioning the T9 input method in relation to the cat phone in some forums so you may be able to search for other solutions if you cannot get it to work.

Sorry for the inconvenience.
