### ISSUE TITLE
Map space to 0 key

### ISSUE THREAD

**Issue by moonman407** [Clam-/TraditionalT9#5]
It was an issue in the early days of texting, one manufacturer would use 0 and space and the other would use the pound key.

I am personally using your app with a Lenovo A588t and would love to have the space mapped to 0 where it is printed. As a long time Nokia user, this also seems the most natural to me.

Any thoughts?

**Comment by Clam-** [comment]
Sorry for the late reply, I didn't get e-mail notification.
Yes over the year the different phones I've had have had different space keys. Just so happened the current phone I have used space on pound.
I could probably make it selectable. I'll look in to it.

**Comment by davouch** [comment]
+1 here

**Comment by Soft-Man** [comment]
try it
http://4pda.ru/forum/index.php?showtopic=517407&st=20#entry47890125

**Comment by Clam-** [comment]
The build that introduced this feature can be found here until it is pushed to the play store:
http://nyanya.org/android/TraditionalT9-git-e08c4a4.apk
