### ISSUE TITLE
Problem with french dictionnary

### ISSUE THREAD

**Issue by K3vain** [Clam-/TraditionalT9#6]
Hello,

I have compiled your update to create an apk file. When i have installed the file, the french dictonnary wasn't found and the application stop to work. It is possible to update your application on google play ?

**Comment by Clam-** [comment]
Hello,

That is unfortunate to hear. You can try the French test build available here: http://nyanya.org/android/TraditionalT9-git-9458c58.apk (this will become the Google Play store version if there's no issues.)
Remember to enable the French language, and then load dictionary.

Let me know how you go.

**Comment by K3vain** [comment]
Hello,

With you compilation, the application runs without problem. The dictionary was loaded with no problem too.

Thank you :)

**Comment by Clam-** [comment]
Cool.
Feel free to create more issues if you get further problems.

Glad I could be of help :)
