### ISSUE TITLE
Mistyping when hitting next letter (button) too soon

### ISSUE THREAD

**Issue by davouch** [Clam-/TraditionalT9#7]
I'm running the august/2015 version of TT9 on Lenovo A558T ([link](http://nyanya.org/android/TraditionalT9-00665c7-FRmissingIcons.apk))

When in non-predictive mode, the phone would mistype when hitting next letter (button) immediately next after the previous letter was typed - i.e. not waiting with the next letter until the previous letter selection onscreen widget would disappear.

"The mistype" inserts (an unwanted) first letter of the next button pressed then it would insert your desired letter from the same button.

Example: I want to type David.
  * for letter "D" I'd press key number 3 one time
    * result: D
  * for letter "a" I'd press key 2 one time
    * result: Da
  * for letter "v" I'd press key 8 three times (it works fine here, for some reason)
    * result: Dav
  * for letter "i" I'd press key 4 three times, the phone types "g" and "i"
    * result: Davgi
  * for letter "d" I'd press key 3 one time
    * result: Davgid

_As noted above this happens only when typing (sanely) fast not waiting for the previous letter to get "stamped" by the system. When typing slowly, everything works._

Here is a short [video](https://goo.gl/photos/4jB9vWeSuyy37pLD7) of how it looks like in real (sorry for my son being a bit nervous along :) ).

**Comment by Clam-** [comment]
Yes, it took me a long time to notice this issue because I mainly use dictionary mode.
I can reproduce it and it's something that I've been meaning to look in to.
I recently got a new device which I'll hopefully use as a chance to tighten up these issues.

Thanks for your time in reporting the issue.

**Comment by Clam-** [comment]
I attempted to quick fix this in 84d8ead but I've been told this doesn't work. I'll continue to look in to it.

**Comment by davouch** [comment]
Thanks!

**Comment by Clam-** [comment]
Hopefully this bug is now fixed.
You can find this commit in this build: http://nyanya.org/android/TraditionalT9-git-d3b10a4.apk

**Comment by davouch** [comment]
Seems working fine to me.
Nice job, sir!
dh
