### ISSUE TITLE
Illustrate selection in Insert Symbol view

### ISSUE THREAD

**Issue by Clam-** [Clam-/TraditionalT9#8]
Currently you can select items with the DPAD, but selection isn't highlighted.
Easiest way to do this would be to make new button images for highlighted state.

**Comment by Clam-** [comment]
Low priority as I can't figure out an easy way to do it without duplicating the images. Don't want a thousand copies of each key.

**Comment by iaros** [comment]
You could consider coloring the selected symbol in different color?

**Comment by Clam-** [comment]
Hmm, changing the text colour of the symbol is certainly possible. That might be a quick and easy fix.
Thanks.
